<?php
// country-profile.php

include 'config.php'; // Ensure the database connection is included

// Array or database query for country list (using your existing $country_map array)
$country_map = $country_map = [
    "Afghanistan" => "🇦🇫",
    "Albania" => "🇦🇱",
    "Algeria" => "🇩🇿",
    "Andorra" => "🇦🇩",
    "Angola" => "🇦🇴",
    "Antigua and Barbuda" => "🇦🇬",
    "Argentina" => "🇦🇷",
    "Armenia" => "🇦🇲",
    "Australia" => "🇦🇺",
    "Austria" => "🇦🇹",
    "Azerbaijan" => "🇦🇿",
    "Bahamas" => "🇧🇸",
    "Bahrain" => "🇧🇭",
    "Bangladesh" => "🇧🇩",
    "Barbados" => "🇧🇧",
    "Belarus" => "🇧🇾",
    "Belgium" => "🇧🇪",
    "Belize" => "🇧🇿",
    "Benin" => "🇧🇯",
    "Bhutan" => "🇧🇹",
    "Bolivia" => "🇧🇴",
    "Bosnia and Herzegovina" => "🇧🇦",
    "Botswana" => "🇧🇼",
    "Brazil" => "🇧🇷",
    "Brunei" => "🇧🇳",
    "Bulgaria" => "🇧🇬",
    "Burkina Faso" => "🇧🇫",
    "Burundi" => "🇧🇮",
    "Cabo Verde" => "🇨🇻",
    "Cambodia" => "🇰🇭",
    "Cameroon" => "🇨🇲",
    "Canada" => "🇨🇦",
    "Central African Republic" => "🇨🇫",
    "Chad" => "🇹🇩",
    "Chile" => "🇨🇱",
    "China" => "🇨🇳",
    "Colombia" => "🇨🇴",
    "Comoros" => "🇰🇲",
    "Republic of the Congo" => "🇨🇬",
    "Democratic Republic of the Congo" => "🇨🇩",
    "Costa Rica" => "🇨🇷",
    "Côte d'Ivoire"=> "🇨🇮",
    "Croatia" => "🇭🇷",
    "Cuba" => "🇨🇺",
    "Cyprus" => "🇨🇾",
    "Czech Republic" => "🇨🇿",
    "Denmark" => "🇩🇰",
    "Djibouti" => "🇩🇯",
    "Dominica" => "🇩🇲",
    "Dominican Republic" => "🇩🇴",
    "East Timor (Timor-Leste)" => "🇹🇱",
    "Ecuador" => "🇪🇨",
    "Egypt" => "🇪🇬",
    "El Salvador" => "🇸🇻",
    "England" => "🏴󠁧󠁢󠁥󠁮󠁧󠁿🇬🇧",
    "Equatorial Guinea" => "🇬🇶",
    "Eritrea" => "🇪🇷",
    "Estonia" => "🇪🇪",
    "Eswatini" => "🇸🇿",
    "Ethiopia" => "🇪🇹",
    "Fiji" => "🇫🇯",
    "Finland" => "🇫🇮",
    "France" => "🇫🇷",
    "Gabon" => "🇬🇦",
    "Gambia" => "🇬🇲",
    "Georgia" => "🇬🇪",
    "Germany" => "🇩🇪",
    "Ghana" => "🇬🇭",
    "Greece" => "🇬🇷",
    "Grenada" => "🇬🇩",
    "Guatemala" => "🇬🇹",
    "Guinea" => "🇬🇳",
    "Guinea-Bissau" => "🇬🇼",
    "Guyana" => "🇬🇾",
    "Haiti" => "🇭🇹",
    "Honduras" => "🇭🇳",
    "Hungary" => "🇭🇺",
    "Iceland" => "🇮🇸",
    "India" => "🇮🇳",
    "Indonesia" => "🇮🇩",
    "Iran" => "🇮🇷",
    "Iraq" => "🇮🇶",
    "Ireland" => "🇮🇪",
    "Israel" => "🇮🇱",
    "Italy" => "🇮🇹",
    "Jamaica" => "🇯🇲",
    "Japan" => "🇯🇵",
    "Jordan" => "🇯🇴",
    "Kazakhstan" => "🇰🇿",
    "Kenya" => "🇰🇪",
    "Kiribati" => "🇰🇮",
    "North Korea" => "🇰🇵",
    "South Korea" => "🇰🇷",
    "Kosovo" => "🇽🇰",
    "Kuwait" => "🇰🇼",
    "Kyrgyzstan" => "🇰🇬",
    "Laos" => "🇱🇦",
    "Latvia" => "🇱🇻",
    "Lebanon" => "🇱🇧",
    "Lesotho" => "🇱🇸",
    "Liberia" => "🇱🇷",
    "Libya" => "🇱🇾",
    "Liechtenstein" => "🇱🇮",
    "Lithuania" => "🇱🇹",
    "Luxembourg" => "🇱🇺",
    "Madagascar" => "🇲🇬",
    "Malawi" => "🇲🇼",
    "Malaysia" => "🇲🇾",
    "Maldives" => "🇲🇻",
    "Mali" => "🇲🇱",
    "Malta" => "🇲🇹",
    "Marshall Islands" => "🇲🇭",
    "Mauritania" => "🇲🇷",
    "Mauritius" => "🇲🇺",
    "Mexico" => "🇲🇽",
    "Micronesia" => "🇫🇲",
    "Moldova" => "🇲🇩",
    "Monaco" => "🇲🇨",
    "Mongolia" => "🇲🇳",
    "Montenegro" => "🇲🇪",
    "Morocco" => "🇲🇦",
    "Mozambique" => "🇲🇿",
    "Myanmar" => "🇲🇲",
    "Namibia" => "🇳🇦",
    "Nauru" => "🇳🇷",
    "Nepal" => "🇳🇵",
    "Netherlands" => "🇳🇱",
    "New Zealand" => "🇳🇿",
    "Nicaragua" => "🇳🇮",
    "Niger" => "🇳🇪",
    "Nigeria" => "🇳🇬",
    "North Macedonia" => "🇲🇰",
    "Northern Ireland" => "🇬🇧",
    "Norway" => "🇳🇴",
    "Oman" => "🇴🇲",
    "Pakistan" => "🇵🇰",
    "Palau" => "🇵🇼",
    "Palestine"=> "🇵🇸",
    "Panama" => "🇵🇦",
    "Papua New Guinea" => "🇵🇬",
    "Paraguay" => "🇵🇾",
    "Peru" => "🇵🇪",
    "Philippines" => "🇵🇭",
    "Poland" => "🇵🇱",
    "Portugal" => "🇵🇹",
    "Qatar" => "🇶🇦",
    "Romania" => "🇷🇴",
    "Russia" => "🇷🇺",
    "Rwanda" => "🇷🇼",
    "Saint Kitts and Nevis" => "🇰🇳",
    "Saint Lucia" => "🇱🇨",
    "Saint Vincent and the Grenadines" => "🇻🇨",
    "Samoa" => "🇼🇸",
    "San Marino" => "🇸🇲",
    "Sao Tome and Principe" => "🇸🇹",
    "Saudi Arabia" => "🇸🇦",
    "Scotland" => "🏴󠁧󠁢󠁳󠁣󠁴󠁿🇬🇧",
    "Senegal" => "🇸🇳",
    "Serbia" => "🇷🇸",
    "Seychelles" => "🇸🇨",
    "Sierra Leone" => "🇸🇱",
    "Singapore" => "🇸🇬",
    "Slovakia" => "🇸🇰",
    "Slovenia" => "🇸🇮",
    "Solomon Islands" => "🇸🇧",
    "Somalia" => "🇸🇴",
    "South Africa" => "🇿🇦",
    "South Sudan" => "🇸🇸",
    "Spain" => "🇪🇸",
    "Sri Lanka" => "🇱🇰",
    "Sudan" => "🇸🇩",
    "Suriname" => "🇸🇷",
    "Sweden" => "🇸🇪",
    "Switzerland" => "🇨🇭",
    "Syria" => "🇸🇾",
    "Taiwan" => "🇹🇼",
    "Tajikistan" => "🇹🇯",
    "Tanzania" => "🇹🇿",
    "Thailand" => "🇹🇭",
    "Togo" => "🇹🇬",
    "Tonga" => "🇹🇴",
    "Trinidad and Tobago" => "🇹🇹",
    "Tunisia" => "🇹🇳",
    "Turkey" => "🇹🇷",
    "Turkmenistan" => "🇹🇲",
    "Tuvalu" => "🇹🇻",
    "Uganda" => "🇺🇬",
    "Ukraine" => "🇺🇦",
    "United Arab Emirates" => "🇦🇪",
    "United Kingdom" => "🇬🇧",
    "United States" => "🇺🇸",
    "Uruguay" => "🇺🇾",
    "Uzbekistan" => "🇺🇿",
    "Vanuatu" => "🇻🇺",
    "Vatican City" => "🇻🇦",
    "Venezuela" => "🇻🇪",
    "Vietnam" => "🇻🇳",
    "Wales" => "🏴󠁧󠁢󠁷󠁬󠁳󠁿🇬🇧",
    "Yemen" => "🇾🇪",
    "Zambia" => "🇿🇲",
    "Zimbabwe" => "🇿🇼"
];
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Country Profiles</title>
    <link rel="stylesheet" href="styles.css">
    <link rel="stylesheet" href="country-profiles-styles.css">
</head>
<body>

    <?php include 'navbar.php'; ?> <!-- Include your NavBar -->

    <section id="main-country-profiles">
        <h1>Country Profiles</h1>
        <p>This is a complete list of countries in our database. Select a country to view its profile.</p>
        <p>(Access to profiles are still a work in progress.)</p>
        <ul>
            <?php foreach ($country_map as $country => $flag): ?>
                <li>
                    <a href="country-profile.php?country=<?php echo urlencode($country); ?>">
                        <?php echo $country . " " . $flag; ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </section>

</body>
</html>